-- MNPS 문제 은행 126문항: 기존 42문항 유지, v2·v3 변형 84문항 추가
-- 실행 전: 006_update_questions_v2.sql 적용된 상태 (42문항 존재)
-- 랜덤 출제 시 슬롯당 1문항 선택으로 42문항 구성, 재검사 시 다른 조합 가능

INSERT INTO questions (id, category, trait, sub_factor, content, question_order, weight, reverse_scored) VALUES
('n1_v2', 'darkTetrad', 'narcissism', 'egoism', '나는 대부분의 사람들보다 능력이 뛰어나다고 스스로 믿는 편이다.', 1, 1.0, false),
('n2_v2', 'darkTetrad', 'narcissism', 'egoism', '주변의 인정이나 칭찬이 없으면 불만스럽고 허전함을 느낀다.', 2, 1.0, false),
('n3_v2', 'darkTetrad', 'narcissism', 'entitlement', '내 수준에 걸맞은 특별 대우를 받는 것은 당연한 권리라고 생각한다.', 3, 1.0, false),
('n4_v2', 'darkTetrad', 'narcissism', 'entitlement', '평범한 삶을 사는 것은 내 정체성과 맞지 않는다.', 4, 1.0, false),
('e1_v2', 'dFactor', NULL, 'egoism', '긴급한 상황에서는 내 이익을 위해 다른 사람의 상황을 뒤로 미룰 수 있다.', 5, 1.0, false),
('e2_v2', 'dFactor', NULL, 'egoism', '다른 사람의 문제보다 내 일이 더 시급하고 중요하다고 느낀다.', 6, 1.0, false),
('e3_v2', 'dFactor', NULL, 'egoism', '결정을 내릴 때 나의 이익을 가장 먼저 고려한다.', 7, 1.0, false),
('en1_v2', 'dFactor', NULL, 'entitlement', '규칙은 상황에 따라 나에게는 유연하게 적용되어도 된다고 본다.', 8, 1.0, false),
('en2_v2', 'dFactor', NULL, 'entitlement', '원하는 것을 얻지 못하면 불공정하다고 느낀다.', 9, 1.0, false),
('en3_v2', 'dFactor', NULL, 'entitlement', '주변 사람들은 내 요구나 기대에 부응해야 한다고 생각한다.', 10, 1.0, false),
('m1_v2', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '중요한 목표를 위해서는 도덕적 원칙을 일시적으로 유보할 수 있다.', 11, 1.0, false),
('m2_v2', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '원하는 결과를 얻기 위해 사람을 설득·영향시키는 것은 실력이다.', 12, 1.0, false),
('m3_v2', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '경쟁 상대의 약점을 활용하는 것은 비도덕적이기보다 전략적이다.', 13, 1.0, false),
('m4_v2', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '새로운 사람을 만날 때 그 사람이 나에게 도움이 될지 먼저 판단한다.', 14, 1.0, false),
('p1_v2', 'darkTetrad', 'psychopathy', 'egoism', '결과를 생각하기보다 당장 하고 싶은 대로 행동하는 편이다.', 15, 1.0, false),
('p2_v2', 'darkTetrad', 'psychopathy', 'spitefulness', '다른 사람이 울거나 괴로워해도 크게 공감이 되지 않는다.', 16, 1.0, false),
('p3_v2', 'darkTetrad', 'psychopathy', NULL, '규칙을 어겨가며 하는 일에서 스릴을 느낀다.', 17, 1.0, false),
('p4_v2', 'darkTetrad', 'psychopathy', 'moralDisengagement', '문제가 생기면 내 책임이라도 상황이나 타인 탓으로 돌리며 빠져나가려 한다.', 18, 1.0, false),
('sc1_v2', 'scenario', 'machiavellianism', 'moralDisengagement', '[상황] 승진 경쟁에서 경쟁자의 치명적 실수를 알게 되었다. 나는 그 정보를 활용해 그를 제거하는 쪽을 택할 수 있다.', 19, 1.0, false),
('sc2_v2', 'scenario', 'narcissism', 'spitefulness', '[상황] 나를 공개적으로 무시한 사람이 있다. 기회가 되면 그 사람을 같은 방식으로 굴욕시키겠다.', 20, 1.0, false),
('sc3_v2', 'scenario', 'narcissism', 'entitlement', '[상황] 팀 성과에서 내 기여가 제대로 인정받지 못했다. 필요하다면 협력을 거부하거나 불만을 드러내겠다.', 21, 1.0, false),
('sc4_v2', 'scenario', 'psychopathy', 'egoism', '[상황] 내가 큰 이득을 보려면 상대방에게 감정적 피해를 줘야 한다. 나는 그 선택을 할 수 있다.', 22, 1.0, false),
('md1_v2', 'dFactor', NULL, 'moralDisengagement', '최종 결과가 좋다면 과정의 작은 부정은 정당화될 수 있다고 본다.', 23, 1.0, false),
('md2_v2', 'dFactor', NULL, 'moralDisengagement', '세상은 서로 이용하는 구조이므로 먼저 움직이는 쪽이 유리하다.', 24, 1.0, false),
('md3_v2', 'dFactor', NULL, 'moralDisengagement', '도덕과 양심은 여유 없는 사람들이나 고수하는 것 같다.', 25, 1.0, false),
('s1_v2', 'darkTetrad', 'sadism', 'spitefulness', '말다툼에서 상대가 당황하거나 굴욕당하는 모습을 보면 쾌감이 든다.', 26, 1.0, false),
('s2_v2', 'darkTetrad', 'sadism', 'spitefulness', '폭력적이거나 잔인한 장면이 나와도 불쾌하기보다 흥미롭게 본다.', 27, 1.0, false),
('s3_v2', 'darkTetrad', 'sadism', 'spitefulness', '농담을 빌미로 상대의 약점을 건드리고 반응을 보는 것을 즐긴다.', 28, 1.0, false),
('s4_v2', 'darkTetrad', 'sadism', 'spitefulness', '잘난 체하는 사람을 무너뜨릴 때 성취감과 희열을 느낀다.', 29, 1.0, false),
('sp1_v2', 'dFactor', NULL, 'spitefulness', '가끔 심심할 때 고의로 논쟁을 걸거나 상대를 자극해 본다.', 30, 1.0, false),
('sp2_v2', 'dFactor', NULL, 'spitefulness', '남이 불행해도 겉으로만 위로하고 속으로는 통쾌할 때가 있다.', 31, 1.0, false),
('sp3_v2', 'dFactor', NULL, 'spitefulness', '내가 조금 손해를 보더라도 싫은 사람이 실패하는 걸 보는 데 만족한다.', 32, 1.0, false),
('v1_v2', 'validation', NULL, NULL, '이 검사에 거짓 없이 솔직하게 응답하고 있다.', 33, 1.0, false),
('m5_v2', 'darkTetrad', 'machiavellianism', 'egoism', '이득이 크다면 비밀을 지킬 의무보다 정보를 활용하는 쪽을 택할 수 있다.', 34, 1.0, false),
('v3_v2', 'validation', NULL, NULL, '나를 더 좋은 사람처럼 보이게 하려고 답을 바꾼 적이 있다.', 35, 1.0, true),
('p5_v2', 'darkTetrad', 'psychopathy', 'moralDisengagement', '거짓말이 탄로나도 당황하지 않고 침착하게 넘어갈 수 있다.', 36, 1.0, false),
('s5_v2', 'darkTetrad', 'sadism', 'spitefulness', '가까운 사람을 통제하기 위해 의도적으로 불안이나 질투를 유발한 적이 있다.', 37, 1.0, false),
('sp4_v2', 'dFactor', NULL, 'spitefulness', '나를 무시한 사람은 반드시 기억했다가 대가를 치르게 하고 싶다.', 38, 1.0, false),
('v7_v2', 'validation', NULL, NULL, '사회적으로 비난받을 만한 생각은 숨기고 답한 적이 있다.', 39, 1.0, true),
('v4_v2', 'validation', NULL, NULL, '지금 선택한 답은 내 실제 생각과 일치한다.', 40, 1.0, false),
('n1b_v2', 'darkTetrad', 'narcissism', 'egoism', '나는 일반인보다 훨씬 우수한 편에 속한다고 생각한다.', 41, 1.0, false),
('m1b_v2', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '목표가 중요할수록 도덕적 기준은 상황에 맞게 조정해도 된다.', 42, 1.0, false),
('n1_v3', 'darkTetrad', 'narcissism', 'egoism', '평균적인 사람들과 비교했을 때 나는 더 뛰어나다고 느낀다.', 1, 1.0, false),
('n2_v3', 'darkTetrad', 'narcissism', 'egoism', '인정받지 못하는 환경에서는 불안하고 초조해진다.', 2, 1.0, false),
('n3_v3', 'darkTetrad', 'narcissism', 'entitlement', '내 능력이라면 특별한 대우를 요구해도 마땅하다고 생각한다.', 3, 1.0, false),
('n4_v3', 'darkTetrad', 'narcissism', 'entitlement', '남들과 동일한 수준의 삶을 사는 것은 나에게 맞지 않는다.', 4, 1.0, false),
('e1_v3', 'dFactor', NULL, 'egoism', '위기 상황에서는 내 이익을 위해 타인의 이익을 희생할 수 있다.', 5, 1.0, false),
('e2_v3', 'dFactor', NULL, 'egoism', '솔직히 말해 타인의 고민보다 내 문제가 더 신경 쓰인다.', 6, 1.0, false),
('e3_v3', 'dFactor', NULL, 'egoism', '어떤 선택이든 나를 최우선에 두고 판단한다.', 7, 1.0, false),
('en1_v3', 'dFactor', NULL, 'entitlement', '규칙이나 순서는 나에게는 예외가 허용될 수 있다고 본다.', 8, 1.0, false),
('en2_v3', 'dFactor', NULL, 'entitlement', '원하는 것을 얻지 못하면 세상이 나에게 불공정하다고 느껴진다.', 9, 1.0, false),
('en3_v3', 'dFactor', NULL, 'entitlement', '주변은 내 기대에 맞춰 움직여 주는 것이 당연하다고 느낀다.', 10, 1.0, false),
('m1_v3', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '큰 성과를 위해서라면 도덕적 원칙을 잠시 내려놓을 수 있다.', 11, 1.0, false),
('m2_v3', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '사람을 내 계획대로 움직여 결과를 얻는 것은 능력의 하나다.', 12, 1.0, false),
('m3_v3', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '경쟁자의 약점을 활용하는 것은 비열함이 아니라 전략이다.', 13, 1.0, false),
('m4_v3', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '사람을 만날 때 "이 사람이 나에게 어떤 가치가 있는가"를 먼저 생각한다.', 14, 1.0, false),
('p1_v3', 'darkTetrad', 'psychopathy', 'egoism', '장기적 결과보다 당장의 욕구를 따라 행동하는 편이다.', 15, 1.0, false),
('p2_v3', 'darkTetrad', 'psychopathy', 'spitefulness', '타인이 감정적으로 힘들어해도 공감이 잘 되지 않는다.', 16, 1.0, false),
('p3_v3', 'darkTetrad', 'psychopathy', NULL, '규칙을 깨는 일에서 오는 스릴을 선호한다.', 17, 1.0, false),
('p4_v3', 'darkTetrad', 'psychopathy', 'moralDisengagement', '내 실수로 문제가 생겨도 책임을 돌리거나 변명하며 빠져나가려 한다.', 18, 1.0, false),
('sc1_v3', 'scenario', 'machiavellianism', 'moralDisengagement', '[상황] 승진 경쟁에서 경쟁자의 치명적 약점을 알게 됐다. 나는 그를 탈락시키는 데 활용할 수 있다.', 19, 1.0, false),
('sc2_v3', 'scenario', 'narcissism', 'spitefulness', '[상황] 나를 망신시킨 사람이 있다. 기회가 오면 그 사람을 공개적으로 깎아내리겠다.', 20, 1.0, false),
('sc3_v3', 'scenario', 'narcissism', 'entitlement', '[상황] 내 기여가 제대로 인정되지 않은 프로젝트라면, 불만을 표출하거나 협조를 줄일 수 있다.', 21, 1.0, false),
('sc4_v3', 'scenario', 'psychopathy', 'egoism', '[상황] 큰 이득을 위해 상대에게 감정적 상처를 줘야 한다면, 나는 그 선택을 할 수 있다.', 22, 1.0, false),
('md1_v3', 'dFactor', NULL, 'moralDisengagement', '결과가 좋다면 과정의 작은 부정은 넘어갈 수 있다고 본다.', 23, 1.0, false),
('md2_v3', 'dFactor', NULL, 'moralDisengagement', '이용당하지 않으려면 먼저 이용하는 쪽이 유리하다.', 24, 1.0, false),
('md3_v3', 'dFactor', NULL, 'moralDisengagement', '양심과 도덕은 여유 있는 사람들의 여유일 뿐이라고 느낄 때가 있다.', 25, 1.0, false),
('s1_v3', 'darkTetrad', 'sadism', 'spitefulness', '상대가 말문이 막혀 당황하는 모습을 보면 묘한 만족감이 든다.', 26, 1.0, false),
('s2_v3', 'darkTetrad', 'sadism', 'spitefulness', '잔혹하거나 폭력적인 콘텐츠를 볼 때 거부감보다 흥미가 더 크다.', 27, 1.0, false),
('s3_v3', 'darkTetrad', 'sadism', 'spitefulness', '상대의 아픈 곳을 건드리는 말을 하고 그 반응을 보는 것을 즐긴다.', 28, 1.0, false),
('s4_v3', 'darkTetrad', 'sadism', 'spitefulness', '잘난 체하는 사람을 무너뜨리는 데서 쾌감을 느낀다.', 29, 1.0, false),
('sp1_v3', 'dFactor', NULL, 'spitefulness', '심심할 때 고의로 말다툼을 하거나 상대를 화나게 해 본 적이 있다.', 30, 1.0, false),
('sp2_v3', 'dFactor', NULL, 'spitefulness', '남이 불행할 때 겉으로는 동정하지만 속으로는 쌤통이라고 느낀다.', 31, 1.0, false),
('sp3_v3', 'dFactor', NULL, 'spitefulness', '손해를 감수하더라도 싫은 사람이 실패하는 모습을 보고 싶다.', 32, 1.0, false),
('v1_v3', 'validation', NULL, NULL, '모든 문항에 거짓 없이 솔직하게 답하고 있다.', 33, 1.0, false),
('m5_v3', 'darkTetrad', 'machiavellianism', 'egoism', '이익이 충분하면 비밀 유지보다 정보를 활용하는 것을 선택할 수 있다.', 34, 1.0, false),
('v3_v3', 'validation', NULL, NULL, '실제보다 더 착하게 보이려고 답을 고른 적이 있다.', 35, 1.0, true),
('p5_v3', 'darkTetrad', 'psychopathy', 'moralDisengagement', '거짓말이 들통나도 당황하지 않고 담담히 대할 수 있다.', 36, 1.0, false),
('s5_v3', 'darkTetrad', 'sadism', 'spitefulness', '친밀한 관계에서 통제권을 갖기 위해 질투나 불안을 유발한 적이 있다.', 37, 1.0, false),
('sp4_v3', 'dFactor', NULL, 'spitefulness', '나를 무시한 사람은 반드시 어떤 형태로든 대가를 치르게 해야 직성이 풀린다.', 38, 1.0, false),
('v7_v3', 'validation', NULL, NULL, '비난받을 만한 생각은 숨기고 답변한 적이 있다.', 39, 1.0, true),
('v4_v3', 'validation', NULL, NULL, '선택한 답은 나의 실제 성격과 맞다.', 40, 1.0, false),
('n1b_v3', 'darkTetrad', 'narcissism', 'egoism', '나는 평균보다 훨씬 뛰어난 사람이라고 생각한다.', 41, 1.0, false),
('m1b_v3', 'darkTetrad', 'machiavellianism', 'moralDisengagement', '목표가 중요하다면 도덕적 기준은 상황에 따라 바꿔도 된다.', 42, 1.0, false)
ON CONFLICT (id) DO NOTHING;
